<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "about".
 *
 * @property int $id
 * @property string $img
 * @property string $tittle
 * @property string|null $description
 */
class About extends \yii\db\ActiveRecord
{
    public $file;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'about';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tittle'], 'required'],
            [['description'], 'string'],
            [['img','tittle'], 'string', 'max' => 255],
            [['file'], 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img' => 'Изображение',
            'file' => 'Изображение',
            'tittle' => 'Заголовок',
            'description' => 'Описание',
        ];
    }

    public function beforeSave($insert)
    {

        if ($file = UploadedFile::getInstance($this, 'file')){
            $dir = Yii::getAlias('@frontend/web/');
            if (file_exists($dir.$this->img)){
                unlink($dir.$this->img);
            }
            $this->img = 'imagesUpload/' . strtotime('now') . '.' .$file->extension;

            $file->saveAs($dir.$this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
