<?php

namespace common\models;

use Yii;
use yii\helpers\Url;
use yii\web\UploadedFile;

/**
 * This is the model class for table "gallerey".
 *
 * @property int $id
 * @property string $img
 */
class Gallerey extends \yii\db\ActiveRecord
{
    public $file_gallerey;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'gallerey';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['img'], 'string', 'max' => 255],
            [['file_gallerey'], 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img' => 'Изображение',
            'file_gallerey' => '',
        ];
    }

    public function getImagesPreview()
    {
        $dir = str_replace('admin','',Url::home(true)).'frontend/web/';
        return $dir.$this->img;

    }

    public function beforeSave($insert)
    {
        if ($file_gallerey = UploadedFile::getInstance($this, 'file_gallerey')){
            $dir = Yii::getAlias('@frontend/web/');
            if (file_exists($dir.$this->img) && $this->img!=null){
                unlink($dir.$this->img);
            }
            $this->img = 'imagesGallerey/' . strtotime('now') . '.' .$file_gallerey->extension;
            $file_gallerey->saveAs($dir.$this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
