<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "ourfruit".
 *
 * @property int $id
 * @property string $img
 * @property string $name
 */
class Ourfruit extends \yii\db\ActiveRecord
{
    public $file_fruit;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'ourfruit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['img', 'name'], 'string', 'max' => 255],
            [['file_fruit'], 'image'],
        ];
    }

    function behaviors()
    {
        return [
            'seo' => [
                'class' => 'dvizh\seo\behaviors\SeoFields',
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'file_fruit' => '',
            'img' => 'Изображение',
            'name' => 'Название товара',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file_fruit = UploadedFile::getInstance($this, 'file_fruit')){
            $dir = Yii::getAlias('@frontend/web/');
            if (file_exists($dir.$this->img) && $this->img!=null){
                unlink($dir.$this->img);
            }
            $this->img = 'imagesOurfruit/' . strtotime('now') . '.' .$file_fruit->extension;
            $file_fruit->saveAs($dir.$this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
