<?php

namespace common\models;

use yii\helpers\Url;
use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "testimonial".
 *
 * @property int $id
 * @property string $img
 * @property string $name
 * @property string $title
 * @property string|null $description
 * @property string|null $status
 */
class Testimonial extends \yii\db\ActiveRecord
{
    public $file_client;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'testimonial';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'title'], 'required'],
            [['description'], 'string'],
            [['img', 'name', 'title', 'status'], 'string', 'max' => 255],
            [['file_client'], 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'img' => 'Изображение',
            'file_client' => '',
            'name' => 'Покупатель',
            'title' => 'Заголовок',
            'description' => 'Описание',
            'status' => 'Первый в карусели (1/0)',
        ];
    }

    public function getImagesPreview()
    {
        $dir = str_replace('admin','',Url::home(true)).'frontend/web/';
        return $dir.$this->img;

    }

    public function beforeSave($insert)
    {
        if ($file_client = UploadedFile::getInstance($this, 'file_client')){
            $dir = Yii::getAlias('@frontend/web/');
            if (file_exists($dir.$this->img) && $this->img!=null){
                unlink($dir.$this->img);
            }
            $this->img = 'imagesClient/' . strtotime('now') . '.' .$file_client->extension;
            $file_client->saveAs($dir.$this->img);
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
